version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 22092003
      MYSQL_USER: docker
      MYSQL_PASSWORD: 22092003
      MYSQL_DATABASE: rest_with_spring_boot_java
      MYSQL_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - daniel-network
  rest-with-spring-boot-java:
    image: daniel2209/rest-with-spring-boot-java
    restart: always
    build: .
    working_dir: /rest-with-spring-boot-and-java
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_java?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 22092003
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - daniel-network
networks:
  daniel-network:
    driver: bridge