server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file: # propriedade customizada criada para dizer o diretório onde será salvo os arquivos
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: 22092003
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
        # properties:
        # hibernate:
      # dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true # habilita multipart para trabalhar com transferência de arquivos
      file-size-threshold: 2KB # tamanho em kb que serão ocupados em memória, após esse passar desse valor irá gravar em disco
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true